app = "pioneering-app-7184"
github = "https://github.com/nida/react-sample/"
id = "38ff3607d6c6bb539a8fd24ee77fd85abe0a3f743d8ca629b635f921cd2c65e16c671901e685cbed1f4184af642653d1"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  image = ""

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  external_port = "80"
  http_checks = []
  internal_port = "3000"
  protocol = "tcp"
  routing_policy = "Latency"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [services.limits]
    cpu = "1"
    memory = "256"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.requests]
    cpu = "0.5"
    memory = "128"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
